{% set name = "psrchive" %}
{% set version = "2024-07-25" %}
{% set sha256 = "01b7562186644b36db17d768db163442cac0bf90bd7081887ad50b6a4e63d90a" %}

package:
  name: "{{ name | lower }}"
  version: "{{ version | replace('-','.') }}"

source:
  # e.g., https://sourceforge.net/projects/psrchive/files/psrchive/2021-01-18/psrchive-2021-01-18.tar.gz/download
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
      - 0004-swig410-flatstatic.patch

build:
  number: 5
  skip: true  # [win or (python_impl == 'pypy')]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
    - perl
    - autoconf
    - automake
    - libtool
    - swig
    - pkg-config
  host:
    - cfitsio
    - pgplot
    - gsl
    - python {{ python }}
    - numpy
    - fftw
    - tempo2
    - libcblas
    - readline
  run:
    - cfitsio
    - pgplot
    - gsl
    - python
    - numpy
    - tempo2
    - fftw
    - readline
test:
  imports:
    - psrchive
  files:
    - test_data/example_psrfits.fits
  commands:
    - pav -h
    - pam -T -e T test_data/example_psrfits.fits
    - test -f test_data/example_psrfits.T
    - python -c "import psrchive; psrchive.Archive_load('test_data/example_psrfits.fits')"

about:
  home: http://psrchive.sourceforge.net/
  license: AFL-2.1
  license_file: COPYING
  summary: PSRCHIVE is a library for the analysis of pulsar astronomical data.
  dev_url: https://sourceforge.net/projects/psrchive/

extra:
  recipe-maintainers:
    - demorest
    - straten
