{% set name = "psrchive" %}
{% set version = "2022-05-14" %}
{% set sha256 = "4d25609837cba1be244fa8adc8f105afe31972f2650bc0b90438862cf35395e1" %}

package:
  name: "{{ name | lower }}"
  version: "{{ version | replace('-','.') }}"

source:
  # e.g., https://sourceforge.net/projects/psrchive/files/psrchive/2021-01-18/psrchive-2021-01-18.tar.gz/download
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or (python_impl == 'pypy')]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - perl
    - autoconf
    - automake
    - libtool
    - swig
  host:
    - cfitsio
    - pgplot
    - gsl
    - python {{ python }}
    - numpy
    - fftw
    - tempo2
    - libcblas
    - readline
  run:
    - cfitsio
    - pgplot
    - gsl
    - python
    - numpy
    - tempo2
    - fftw
    - readline
test:
  files:
    - test_data/example_psrfits.fits
  commands:
    - pav -h
    - pam -T -e T test_data/example_psrfits.fits
    - test -f test_data/example_psrfits.T
  imports:
    - psrchive

about:
  home: http://psrchive.sourceforge.net/
  license: AFL-2.1
  license_file: COPYING
  summary: PSRCHIVE is a library for the analysis of pulsar astronomical data.
  dev_url: https://sourceforge.net/projects/psrchive/

extra:
  recipe-maintainers:
    - demorest
    - straten
