{% set name = "psrchive" %}
{% set version = "9999-99-99" %}
{% set sha256 = "0018b6ce4219567b1dada2f86b5df272605ce1e7abbb03d52716d8d535f9f426" %}

package:
  name: "{{ name | lower }}"
  version: "{{ version | replace('-','.') }}"

source:
  # e.g., https://gitlab.com/pulsar-astronomy/psrchive/-/releases/2026-08-15/downloads/psrchive-2026-08-15.tar.gz
  url: https://gitlab.com/pulsar-astronomy/{{ name }}/-/releases/{{ version }}/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
      - 0007-reference-operator.patch  # [osx]
      - 0008-basename.patch  # [osx]
      - 0009-epsic-complex.patch  # [osx]
      - 0010-python3-c-api.patch

build:
  number: 0
  skip: true  # [win or (python_impl == 'pypy') or osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
    - perl
    - autoconf
    - automake
    - libtool
    - swig
    - pkg-config
  host:
    - cfitsio
    - pgplot
    - gsl
    - python {{ python }}
    - numpy
    - fftw
    - tempo2
    - libcblas
    - readline
  run:
    - cfitsio
    - pgplot
    - gsl
    - python
    - numpy
    - tempo2
    - fftw
    - readline
test:
  imports:
    - psrchive
  files:
    - test_data/example_psrfits.fits
  commands:
    - pav -h
    - pam -T -e T test_data/example_psrfits.fits
    - test -f test_data/example_psrfits.T
    - python -c "import psrchive; psrchive.Archive_load('test_data/example_psrfits.fits')"

about:
  home: https://psrchive.readthedocs.io/en/latest/
  license: AFL-2.1
  license_file: COPYING
  summary: PSRCHIVE is a library for the analysis of pulsar astronomical data.
  dev_url: https://gitlab.com/pulsar-astronomy/psrchive

extra:
  recipe-maintainers:
    - demorest
    - straten
